spring:
  application:
    name: podcast-back
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  data:
    redis:
      host: localhost
      port: 6379
      password: 162003
      database: 1
      timeout: 6000ms

app:
  upload:
    dir: uploads/locutores